// <auto-generated />
using Gymotivate.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Gymotivate.Migrations
{
    [DbContext(typeof(BancoContext))]
    [Migration("20231019115345_removertabelas")]
    partial class removertabelas
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Gymotivate.Models.CadastreModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Cadastre");
                });

            modelBuilder.Entity("Gymotivate.Models.ConquistasModel", b =>
                {
                    b.Property<int>("ConquistasId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ConquistasId"));

                    b.Property<int>("NameConquistasId")
                        .HasColumnType("int");

                    b.Property<bool>("PossuiConquista")
                        .HasColumnType("bit");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("ConquistasId");

                    b.HasIndex("NameConquistasId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Conquistas");
                });

            modelBuilder.Entity("Gymotivate.Models.DiasSemanaModel", b =>
                {
                    b.Property<int>("DiaSemanaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DiaSemanaId"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DiaSemanaId");

                    b.ToTable("DiasSemana");
                });

            modelBuilder.Entity("Gymotivate.Models.ExerciciosModel", b =>
                {
                    b.Property<int>("ExercicioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ExercicioId"));

                    b.Property<int>("DiasSemanaId")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ExercicioId");

                    b.HasIndex("DiasSemanaId");

                    b.ToTable("Exercicios");
                });

            modelBuilder.Entity("Gymotivate.Models.GamesModel", b =>
                {
                    b.Property<int>("GamesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GamesId"));

                    b.Property<int>("AcertosBracos")
                        .HasColumnType("int");

                    b.Property<int>("AcertosCostas")
                        .HasColumnType("int");

                    b.Property<int>("AcertosPeitos")
                        .HasColumnType("int");

                    b.Property<int>("AcertosPernas")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("GamesId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Acertos");
                });

            modelBuilder.Entity("Gymotivate.Models.GrupoConquistasModel", b =>
                {
                    b.Property<int>("GroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GroupId"));

                    b.Property<int>("GroupExpTotal")
                        .HasColumnType("int");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GroupId");

                    b.ToTable("GrupoConquistas");
                });

            modelBuilder.Entity("Gymotivate.Models.NameConquistasModel", b =>
                {
                    b.Property<int>("NameConquistasId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NameConquistasId"));

                    b.Property<int>("ConquistaExp")
                        .HasColumnType("int");

                    b.Property<int>("GrupoConquistasGroupId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Tier")
                        .HasColumnType("int");

                    b.HasKey("NameConquistasId");

                    b.HasIndex("GrupoConquistasGroupId");

                    b.ToTable("NameConquistas");
                });

            modelBuilder.Entity("Gymotivate.Models.TreinoExercicioModel", b =>
                {
                    b.Property<int>("TreinoExercicioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TreinoExercicioId"));

                    b.Property<int>("DiaSemanaId")
                        .HasColumnType("int");

                    b.Property<int>("ExercicioId")
                        .HasColumnType("int");

                    b.Property<int>("TreinoId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("TreinoExercicioId");

                    b.HasIndex("DiaSemanaId");

                    b.HasIndex("ExercicioId");

                    b.HasIndex("TreinoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("TreinoExercicio");
                });

            modelBuilder.Entity("Gymotivate.Models.TreinosModel", b =>
                {
                    b.Property<int>("TreinosId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TreinosId"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TreinosId");

                    b.ToTable("Treinos");
                });

            modelBuilder.Entity("Gymotivate.Models.ConquistasModel", b =>
                {
                    b.HasOne("Gymotivate.Models.NameConquistasModel", "NameConquistas")
                        .WithMany("Conquistas")
                        .HasForeignKey("NameConquistasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gymotivate.Models.CadastreModel", "Usuario")
                        .WithMany("Conquistas")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NameConquistas");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Gymotivate.Models.ExerciciosModel", b =>
                {
                    b.HasOne("Gymotivate.Models.DiasSemanaModel", "DiasSemana")
                        .WithMany("Exercicios")
                        .HasForeignKey("DiasSemanaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DiasSemana");
                });

            modelBuilder.Entity("Gymotivate.Models.GamesModel", b =>
                {
                    b.HasOne("Gymotivate.Models.CadastreModel", "Usuario")
                        .WithMany("Games")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Gymotivate.Models.NameConquistasModel", b =>
                {
                    b.HasOne("Gymotivate.Models.GrupoConquistasModel", "GrupoConquistas")
                        .WithMany("ConquistasName")
                        .HasForeignKey("GrupoConquistasGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GrupoConquistas");
                });

            modelBuilder.Entity("Gymotivate.Models.TreinoExercicioModel", b =>
                {
                    b.HasOne("Gymotivate.Models.DiasSemanaModel", "DiaSemana")
                        .WithMany("TreinoExercicios")
                        .HasForeignKey("DiaSemanaId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Gymotivate.Models.ExerciciosModel", "Exercicio")
                        .WithMany("TreinoExercicios")
                        .HasForeignKey("ExercicioId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Gymotivate.Models.TreinosModel", "Treino")
                        .WithMany("TreinoExercicios")
                        .HasForeignKey("TreinoId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Gymotivate.Models.CadastreModel", "Usuario")
                        .WithMany("TreinoExercicios")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("DiaSemana");

                    b.Navigation("Exercicio");

                    b.Navigation("Treino");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Gymotivate.Models.CadastreModel", b =>
                {
                    b.Navigation("Conquistas");

                    b.Navigation("Games");

                    b.Navigation("TreinoExercicios");
                });

            modelBuilder.Entity("Gymotivate.Models.DiasSemanaModel", b =>
                {
                    b.Navigation("Exercicios");

                    b.Navigation("TreinoExercicios");
                });

            modelBuilder.Entity("Gymotivate.Models.ExerciciosModel", b =>
                {
                    b.Navigation("TreinoExercicios");
                });

            modelBuilder.Entity("Gymotivate.Models.GrupoConquistasModel", b =>
                {
                    b.Navigation("ConquistasName");
                });

            modelBuilder.Entity("Gymotivate.Models.NameConquistasModel", b =>
                {
                    b.Navigation("Conquistas");
                });

            modelBuilder.Entity("Gymotivate.Models.TreinosModel", b =>
                {
                    b.Navigation("TreinoExercicios");
                });
#pragma warning restore 612, 618
        }
    }
}
